name: "测试构建"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建docker
    steps:
      - name: pull centos
        run: docker pull centos
        
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses:  ${{ secrets.DOCKERHUB_USERNAME }}/docker_buildx@master
#         docker/setup-buildx-action@v1
      
        with:
          publish: true
          imageName: ${{ secrets.DOCKERHUB_USERNAME }}/elmmb
          dockerFile: images/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          # platform: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          tag: 2.6
          dockerUser: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}
